# Generated by Django 4.2.14 on 2024-07-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_built', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'years',
            },
        ),
    ]
